import json
import os
import glob

# 预设的高频词汇映射表，确保翻译质量
TRANSLATIONS = {
    "stats.navigationTitleMonitor": "Resource Monitor",
    "stats.tabPerf": "Performance",
    "stats.tabStorage": "Storage",
    "stats.tokenTrend": "Token Usage Trend",
    "stats.faithfulness": "Faithfulness",
    "stats.relevance": "Relevance",
    "stats.precision": "Precision",
    "stats.benchmark": "Benchmark",
    "stats.provenance": "Knowledge Provenance",
    "stats.storageDistribution": "Storage Distribution",
    "stats.totalStorage": "Total Storage",
    "stats.imported": "Imported",
    "stats.manuallyCreated": "Self-created",
    "stats.exportedRecent": "Recently Exported",
    "stats.cleanupAction": "Cleanup Database",
    "stats.cleanedPrefix": "Cleaned",
    "stats.cleanedSuffix": "items",
    "stats.aiResources": "AI Resources",
    "stats.perfAndQuality": "Performance & Quality",
    "page.aiInsights": "AI Insights",
    "page.aiInsights.desc": "Insights generated by AI based on content",
    "page.count": "Page Count",
    "page.history": "History",
    "page.history.none": "No history",
    "page.related.ai": "AI Related",
    "page.related.manual": "Manual Links",
    "page.source.title": "Source",
    "page.ai.lab": "AI Lab",
    "dashboard.title": "Dashboard",
    "dashboard.hotTopics": "Hot Topics",
    "dashboard.dailyInsights": "Daily Insights",
    "ai.status.scanning": "Scanning Knowledge Base...",
    "ai.status.thinking": "AI is thinking...",
    "aitask.scanTaskName": "Library Scan",
    "aitask.noRunning": "No active tasks",
    "search.diagnostics": "Search Diagnostics",
    "search.showAll": "Show All",
    "security.lockVault": "Lock Vault",
    "security.unlock": "Unlock",
    "security.vaultLocked": "Vault Locked",
    "misc.aiThinking": "AI is thinking...",
    "misc.colon": ": ",
    "misc.separator": " · ",
    "misc.unitTenThousand": "10k",
    "misc.dragToSort": "Drag to reorder",
    "lint.aiScanning": "AI Scanning...",
    "lint.center.title": "Lint Center",
    "ingest.ecoIndexingLowPower": "Low Power Mode Indexing",
    "prompt.report": "Report Generation",
    "prompt.summary": "Summary",
    "prompt.mindmap": "Mind Map",
    "prompt.quiz": "Quiz",
    "prompt.slides": "Slides",
}

def fix_xcstrings(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
            
    strings = data.get('strings', {})
    fixed_count = 0
    
    for key, content in strings.items():
        localizations = content.setdefault('localizations', {})
        if 'en' not in localizations:
            # 1. 优先使用预设翻译
            if key in TRANSLATIONS:
                val = TRANSLATIONS[key]
            # 2. 如果是符号或纯英文 Key，直接复用
            elif all(ord(c) < 128 for c in key) and not any(c in key for c in ' .'):
                val = key
            # 3. 如果有中文，且是格式化字符（包含%@等），复用中文里的符号结构但保持原样
            elif 'zh-Hans' in localizations:
                zh_val = localizations['zh-Hans'].get('stringUnit', {}).get('value', "")
                if zh_val and all(ord(c) < 128 for c in zh_val):
                    val = zh_val
                else:
                    # 最后的兜底：如果是空或者是中文，暂时使用 Key 或 Source
                    val = key if not zh_val else zh_val
            else:
                val = key
                
            localizations['en'] = {
                "stringUnit": {
                    "state": "translated",
                    "value": val
                }
            }
            fixed_count += 1
            
    if fixed_count > 0:
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            
    return fixed_count

all_xcstrings = glob.glob('Sources/Localization/*.xcstrings')
total_fixed = 0

for path in all_xcstrings:
    count = fix_xcstrings(path)
    if count > 0:
        print(f"Fixed {count} strings in {path}")
        total_fixed += count

print(f"\nTotal English localizations fixed: {total_fixed}")
